spring:
  application:
    name: authservice
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8083
grpc:
  client:
    user-service:
      address: "discovery:///userservice"
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    rate-service:
      address: "discovery:///rateservice"
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
jwt:
  accessToken: "qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=="
  refreshToken: "qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=="
