version: "3.8"

services:
  user-acc-db:
    image: "postgres:13"
    container_name: "user-acc-db"
    environment:
      - "POSTGRES_USER=postgres"
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - "POSTGRES_DB=postgres"
  discovery-service:
    build: ./discovery-service/
    hostname: "mainserver"
    image: "scb-wind2022/discovery-service:1.0"
    container_name: "discovery-server"
    profiles: ["indocker"]
    ports:
      - 8761:8761
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://mainserver:8761/eureka/"
  gate-service:
    build: ./gateway/
    image: "scb-wind2022/gateway:1.0"
    container_name: "gateway"
    depends_on:
      - discovery-service
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://mainserver:8761/eureka/"
  user-service:
    build: ./user-service/
    image: "scb-wind2022/user-service:1.0"
    container_name: "user-service"
    depends_on:
      - user-acc-db
      - discovery-service
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://mainserver:8761/eureka/"
      - "spring.datasource.url=jdbc:postgresql://user-acc-db:5432/postgres"
  auth-service:
    build: ./auth-service/
    image: "scb-wind2022/auth-service:1.0"
    container_name: "auth-service"
    depends_on:
      - discovery-service
      - user-service
    ports:
      - 8083:8083
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://mainserver:8761/eureka/"
  rate-service:
    build: ./rate-service/
    image: "scb-wind2022/rate-service:1.0"
    container_name: "rate-service"
    depends_on:
      - discovery-service
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://mainserver:8761/eureka/"
#  redis:
#
#    hostname: "redisserver"
#    image: 'bitnami/redis:latest'
#    ports:
#      - 6379:6379
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
