spring:
  application:
    name: userservice
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=userservice
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 0
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: "http://localhost:8761/eureka"
grpc:
  server:
    port: 0
