openapi: '3.0.3'
info:
  title: Personal Financial Office Личный финансовый кабинет
  version: 1.0.0
servers:
  - url: http://localhost:8083
tags:
  - name: auth
    description: Регистрация, аутентификация пользователя
  - name: user
    description: Администрирование пользователей
  - name: account
    description: Выполнение операций со счетами пользователей
  - name: rate
    description: Информация о курсах валют
  - name: trade
    description: Торговые операции с валютами

paths:
  /api/v1/auth/register:
    post:
      summary: Регистрация пользователя
      operationId: register
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
  /api/v1/auth/login:
    post:
      summary: Аутентификация пользователя
      operationId: login
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtResponse'

  /api/v1/users:
    post:
      summary: Получить список пользователей
      operationId: getUsers
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPageRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPageResponse'
  /api/v1/users/{id}:
    get:
      summary: Получить пользователя по идентификатору
      operationId: getUserById
      tags:
        - user
      parameters:
        - in: path
          name: id
          description: Идентификатор пользователя
          required: true
          schema:
            type: integer
            format: int64
          example: 333
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
    put:
      summary: Изменить пользователя
      operationId: updateUser
      tags:
        - user
      parameters:
        - in: path
          name: id
          description: Идентификатор пользователя
          required: true
          schema:
            type: integer
            format: int64
          example: 333
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
    delete:
      summary: Удалить пользователя
      operationId: deleteUser
      tags:
        - user
      parameters:
        - in: path
          name: id
          description: Идентификатор пользователя
          required: true
          schema:
            type: integer
            format: int64
          example: 333
      responses:
        '200':
          description: OK
  /api/v1/users/enable:
    post:
      summary: Активация / блокирование пользователя
      operationId: block
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserEnableRequest'
      responses:
        '200':
          description: OK
  /api/v1/users/password:
    post:
      summary: Изменить пароль пользователя
      operationId: updatePassword
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePwdRequest'
      responses:
        '200':
          description: OK

  /api/v1/accounts/users/{id}:
    get:
      summary: Получить информацию по счетам пользователя
      operationId: getAccountsByUserId
      tags:
        - account
      parameters:
        - in: path
          name: id
          description: Идентификатор пользователя
          required: true
          schema:
            type: integer
            format: int64
          example: 333
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountResponse'
  /api/v1/accounts/{id}:
    get:
      summary: Получить информацию по счету
      operationId: getAccountById
      tags:
        - account
      parameters:
        - in: path
          name: id
          description: Идентификатор счета
          required: true
          schema:
            type: integer
            format: int64
          example: 333
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
    delete:
      summary: Удалить счет пользователя
      operationId: deleteAccountById
      tags:
        - account
      parameters:
        - in: path
          name: id
          description: Идентификатор счета
          required: true
          schema:
            type: integer
            format: int64
          example: 333
      responses:
        '200':
          description: OK
  /api/v1/accounts/:
    post:
      summary: Создать новый счет
      operationId: createAccount
      tags:
        - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
  /api/v1/accounts/sum/:
    patch:
      summary: Изменить сумму на счете
      operationId: updateAccountSum
      tags:
        - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountSumRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
  /api/v1/accounts/enable:
    post:
      summary: Активация / блокирование счета пользователя
      operationId: enableAccount
      tags:
        - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountEnableRequest'
      responses:
        '200':
          description: OK

  /api/v1/rate/current:
    post:
      summary: текущий курс валюты
      operationId: getCurrencyRate
      tags:
        - rate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CurrentCurrencyRateRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurrencyRateResponse'


components:
  schemas:
    CreateUserRequest:
      type: object
      description: Запрос регистрации пользователя
      properties:
        email:
          type: string
          description: Логин пользователя
          example: ivanov
        password:
          type: string
          description: Пароль
          example: secret1E6
        firstName:
          type: string
          description: Имя пользователя
          example: Сергей
        lastName:
          type: string
          description: Фамилия пользователя
          example: Иванов
        phone:
          type: string
          description: Телефон пользователя
          example: 8(999)0010001
    UpdateUserRequest:
      type: object
      description: Запос обновлеения информации пользователя
      properties:
        email:
          type: string
          description: Логин пользователя
          example: ivanov
        firstName:
          type: string
          description: Имя пользователя
          example: Сергей
        lastName:
          type: string
          description: Фамилия пользователя
          example: Иванов
        phone:
          type: string
          description: Телефон пользователя
          example: 8(999)0010001
    AuthRequest:
      type: object
      description: Данные для аутентификации
      properties:
        email:
          type: string
          description: Логин пользователя
          example: ivanov
        password:
          type: string
          description: Пароль
          example: secret1E6
    UpdatePwdRequest:
      type: object
      description: Данные для аутентификации
      properties:
        email:
          type: string
          description: Логин пользователя
          example: ivanov
        oldPassword:
          type: string
          description: Пароль
          example: secret1E6
        newPassword:
          type: string
          description: Пароль
          example: newSecret
    JwtResponse:
      type: object
      description: Токен авторизации
      properties:
        accessToken:
          type: string
          description: Токен авторизации
          example: 1fn3459gf3p_23mj54p-5PONO(mk'
        refreshToken:
          type: string
          description: Токен на запрос нового токена авторизации
          example: f35=kvfr3v3ervkMPOnj4-JO()Ll''
    UserEnableRequest:
      type: object
      description: Активация / блокировка пользователя
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор счета
          example: 465
        enable:
          type: boolean
          description: Доступность пользователя (возможность работы, значения true / false)
          example: true
    UserResponse:
      type: object
      description: Данные пользователя
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор задания
          example: 45
        email:
          type: string
          description: Логин пользователя
          example: ivanov
        firstName:
          type: string
          description: Имя пользователя
          example: Сергей
        lastName:
          type: string
          description: Фамилия пользователя
          example: Иванов
        phone:
          type: string
          description: Телефон пользователя
          example: 8(999)0010001
        enable:
          type: boolean
          description: Доступность пользователя (возможность работы, значения true / false)
          example: true
    UserPageRequest:
      type: object
      description: Запрос страницы списка пользователей
      properties:
        page:
          description: Номер страницы
          type: integer
          example: 1
        size:
          description: Размер страницы (количество пользователей на странице)
          type: integer
          example: 20
    UserPageResponse:
      type: object
      description: Страница списка пользователей
      properties:
        content:
          description: Список пользователей
          type: array
          items:
            $ref: '#/components/schemas/UserResponse'
        page:
          description: Номер страницы
          type: integer
          example: 1
        size:
          description: Размер страницы (количество пользователей на странице)
          type: integer
          example: 20
        totalItems:
          description: Всего пользователей
          type: integer
          format: int64
          example: 2
        totalPages:
          description: Всего страниц
          type: integer
          example: 1

    CreateAccountRequest:
      type: object
      description: Запрос на создание счета пользователя
      properties:
        currencyCharCode:
          type: string
          description: Символьный код валюты
          example: USD
    AccountResponse:
      type: object
      description: Данные счета пользователя
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор счета
          example: 465
        userId:
          type: integer
          format: int64
          description: Идентификатор пользователя
          example: 45
        currencyCharCode:
          type: string
          description: Символьный код валюты
          example: USD
        sum:
          type: number
          description: Сумма на счете
          example: 0.00
        enable:
          type: boolean
          description: Доступность счета
          example: true
    AccountSumRequest:
      type: object
      description: Запрос на изменение суммы на счете пользователя
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор счета
          example: 465
        userId:
          type: integer
          format: int64
          description: Идентификатор пользователя
          example: 45
        currencyCharCode:
          type: string
          description: Символьный код валюты
          example: USD
        sum:
          type: number
          description: Сумма на счете
          example: 0.00
    AccountEnableRequest:
      type: object
      description: Активация / блокировка счета пользователя
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор счета
          example: 465
        enable:
          type: boolean
          description: Доступность счета пользователя (возможность работы, значения true / false)
          example: true

    CurrentCurrencyRateRequest:
      type: object
      description: Запрос текущего курса валют
      properties:
        charCode:
          type: string
          description: Символьный код валюты
          example: USD
    CurrencyRateResponse:
      type: object
      description: Курс валюты
      properties:
        id:
          type: string
          description: Идентификатор
          example: R01235
        numCode:
          type: string
          description: Цифровой код валюты
          example: 840
        charCode:
          type: string
          description: Символьный код валюты
          example: USD
        nominal:
          type: integer
          description: Номинал
          example: 1
        name:
          type: string
          description: Наименование валюты
          example: Доллар США
        value:
          type: number
          description: Курс
          example: 60,8685
