server:
  port: 0
spring:
  application:
    name: rateservice
eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"
    fetch-registry: true
    register-with-eureka: true
grpc:
  server:
    port: 0
cb:
  url: https://www.cbr.ru/scripts/XML_daily.asp
