server:
  port: 0
spring:
  application:
    name: rateservice
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"
    fetch-registry: true
    register-with-eureka: true
grpc:
  client:
    user-service:
      address: "discovery:///userservice"
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
  server:
    port: 0
cb:
  url:
    daily: https://www.cbr.ru/scripts/XML_daily.asp
    dynamic: https://www.cbr.ru/scripts/XML_dynamic.asp

